### ISSUE TITLE
Import statements missing from documentation

### ISSUE THREAD

**Issue by svnlto** [ClouDNS/terraform-provider-cloudns#5]
As per issue #4, imports are meant to work now if I got that right.
However, the provider documentation lacks import documentation.

**Comment by Venkoul99** [comment]
Hello, we have updated the README with the import usage. If you have any additional questions or encounter issues, please feel free to reach out to us.

**Comment by svnlto** [comment]
I was expecting an update in the Terraform registry. [here](https://registry.terraform.io/providers/ClouDNS/cloudns/latest/docs/resources)
The registry still needs the zone resource docs; neither are the import statements documented.

**Comment by Venkoul99** [comment]
Hello, we have released a new version v1.0.5 of the Terraform provider, and the documentation has been updated: [ClouDNS Terraform Provider Documentation](https://registry.terraform.io/providers/ClouDNS/cloudns/latest/docs). If you encounter any issues or have any questions, please don't hesitate to reach out to us for support.

**Comment by Venkoul99** [comment]
We are closing this issue for now. Thank you for your attention and understanding!
