### ISSUE TITLE
DNS failover check with srcaddrs

### ISSUE THREAD

**Issue by sempervictus** [ClouDNS/terraform-provider-cloudns#8]
Utilizing the DNS failover checks from TF would be very handy to handle HA service configurations dynamically.
Since such checks tend to connect to ports, it would be nice for the resource & data source to have source addresses from which the checks would come as an attribute to be referenced by security group configurations for the services being checked.

**Comment by Venkoul99** [comment]
Hello, we have now added Failover support in our Terraform provider. You can find the documentation on the following page:

https://registry.terraform.io/providers/ClouDNS/cloudns/latest/docs/resources/dns_failover

**Comment by Venkoul99** [comment]
We'll go ahead and close this issue for now. If you encounter any further problems or have any other questions, please don't hesitate to reach out to us again.
